trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TestSuiteExecution
  displayName: 'Test Suite Execution'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.17.0'
    displayName: 'Install Node.js'

  - script: npm install --global yarn
    displayName: 'Yarn installation'

  - script: yarn
    displayName: 'Install dependencies'

  - script: npm install -g allure-commandline --save-dev
    displayName: 'Install allure commandline'

  - script: yarn testapi
    displayName: 'Run API tests'
    continueOnError: true

  - script: yarn testui
    displayName: 'Run UI tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'XUnit'
      testResultsFiles: 'api/reports/test-results.xml'
      failTaskOnFailedTests: false
      failTaskOnMissingResultsFile: true
      testRunTitle: 'API Test Run $(System.Date)'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'XUnit'
      testResultsFiles: 'ui/reports/test-results.xml'
      failTaskOnFailedTests: false
      failTaskOnMissingResultsFile: true
      testRunTitle: 'API Test Run $(System.Date)'

  - task: PublishAllureReport@1
    inputs:
      testResultsDir: 'allure-results'
      reportName: 'Allure Test Reports'