trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.17.0'
  displayName: 'Install Node.js'

- script: npm install --global yarn
  displayName: 'Yarn installation'

- script: yarn
  displayName: 'Install dependencies'

- script: npm install -g allure-commandline --save-dev
  displayName: 'Install allgure commandlinne'

- script: yarn testapi
  displayName: 'Run API tests'

- script: yarn testui
  displayName: 'Run UI tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: 'api/reports/test-results.xml'
    failTaskOnFailedTests: false
    failTaskOnMissingResultsFile: true
    testRunTitle: 'API Test Run $(System.Date)'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: 'ui/reports/test-results.xml'
    failTaskOnFailedTests: false
    failTaskOnMissingResultsFile: true
    testRunTitle: 'API Test Run $(System.Date)'

- task: PublishAllureReport@1
  inputs:
    allureVersion: '3.3.0'
    testResultsDir: 'allure-results'
    reportName: 'Allure Test Reports'